theme: jekyll-theme-time-machine
title: Bienvenido a la p치gina del curso BIO 4022. An치lisis y manipulaci칩n de datos en R
description: En esta pagina se mantendr치n actualizandos los contenidos del curso de R para los programas de doctorado de la Universidad Catolica de Chile
